// AUTO-GENERATED by packages/design-tokens/scripts/generate.mjs — do not edit by hand.
// Source: tokens/typography.css · Regenerate: npm run tokens

/* eslint-disable */
// The composite `ty-*` utilities, as TOKEN NAMES.
// Resolve them against the scales in ./tokens.generated. A host turns a spec into
// whatever its platform calls a text style; this file takes no view on that.
//
// `leadingTablet` is present where typography.css overrides the line height at
// 48rem. Read it or do not — but it is here, rather than dropped in transcription.
export const typographySpecs = {
  "text-article": {
    "family": "serif",
    "weight": "normal",
    "size": "text-article",
    "tracking": "wider",
    "leading": "looser"
  },
  "text-s": {
    "family": "sans",
    "weight": "normal",
    "size": "text-s",
    "tracking": "wider",
    "leading": "loose"
  },
  "text-m": {
    "family": "sans",
    "weight": "normal",
    "size": "text-m",
    "tracking": "wide",
    "leading": "loose"
  },
  "text-l": {
    "family": "sans",
    "weight": "normal",
    "size": "text-l",
    "tracking": "wide",
    "leading": "relaxed"
  },
  "headline-xs": {
    "family": "sans",
    "weight": "bold",
    "size": "headline-xs",
    "tracking": "wider",
    "leading": "loose"
  },
  "headline-s": {
    "family": "sans",
    "weight": "bold",
    "size": "headline-s",
    "tracking": "wider",
    "leading": "loose",
    "leadingTablet": "normal"
  },
  "headline-m": {
    "family": "sans",
    "weight": "bold",
    "size": "headline-m",
    "tracking": "normal",
    "leading": "snug"
  },
  "headline-l": {
    "family": "sans",
    "weight": "bold",
    "size": "headline-l",
    "tracking": "tight",
    "leading": "tight"
  },
  "headline-xl": {
    "family": "sans",
    "weight": "bold",
    "size": "headline-xl",
    "tracking": "tighter",
    "leading": "tight",
    "leadingTablet": "tighter"
  },
  "headline-xxl": {
    "family": "sans",
    "weight": "bold",
    "size": "headline-xxl",
    "tracking": "tighter",
    "leading": "tight",
    "leadingTablet": "tighter"
  },
  "button": {
    "family": "sans",
    "weight": "bold",
    "size": "text-button",
    "tracking": "wider",
    "leading": "loose"
  }
} as const;

export type TypoVariant = keyof typeof typographySpecs;
