import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { ROOT } from '../plugin/collect.ts';
import { NOT_DRAWN } from '../src/components/direct-ids.ts';

const HANDBOOK = join(ROOT, 'apps/handbook');
const API = join(HANDBOOK, 'content/api.generated.json');
const REGISTRY = readFileSync(join(HANDBOOK, 'src/components/direct.tsx'), 'utf8');
const PREVIEW = readFileSync(join(HANDBOOK, 'src/components/DirectPreview.tsx'), 'utf8');
const RECIPE = readFileSync(join(HANDBOOK, 'vite.app.mjs'), 'utf8');
const CATALOGUE = readFileSync(join(ROOT, 'apps/mobile/src/gallery/catalogue.tsx'), 'utf8');

/**
 * What the handbook draws itself, held against what the app actually has.
 *
 * `direct-ids.ts` is imported and `direct.tsx` is read as text, which is the
 * split the whole file turns on: the exceptions are plain data, the registry is
 * over React Native components, and a test that imported the second would need
 * the app's entire toolchain to answer a question about strings.
 *
 * How many components *build* is not asserted anywhere, and that is deliberate:
 * `scripts/measure-direct.mjs` answers it, the answer moves when react-native,
 * expo or Rolldown move, and a check that reddens for an upstream release gets
 * switched off. What is asserted here is what this repository owns.
 */
describe('the components the handbook draws', () => {
  /**
   * The roster is the app's, and this is the fact that makes the rest of the
   * file short.
   *
   * ADR 0027 shipped two entries typed out by hand. ADR 0028 replaced them with
   * `apps/mobile/src/gallery/catalogue.tsx`, which already says what every
   * component is shown with, in the props' own words, and which the app's own
   * `__tests__/gallery-catalogue.test.ts` fails on when a component is missing.
   * A second list here would be the two copies AGENTS.md exists to prevent, and
   * it would be the copy nobody edits.
   */
  it('takes its specimens from the app’s own catalogue rather than copying them', () => {
    expect(REGISTRY).toMatch(/from '@\/gallery\/catalogue'/);
    // A specimen written here would be a second answer to "what does this
    // component look like", which is exactly what the import is for.
    expect(REGISTRY).not.toContain('specimens: [');
  });

  it('names only components the app really has, as its exceptions', () => {
    if (!existsSync(API)) {
      // Generated by `npm run api`, which the build runs first and which a fresh
      // clone has not run. Green on a developer's machine and red in CI is worse
      // than skipped in both.
      console.log('skipped: content/api.generated.json is not built');
      return;
    }
    const api = JSON.parse(readFileSync(API, 'utf8')) as {
      components: { groups: { name: string; components: { name: string }[] }[] };
    };
    const known = new Set(
      api.components.groups.flatMap((group) =>
        group.components.map((component) => `${group.name}/${component.name}`),
      ),
    );

    expect(Object.keys(NOT_DRAWN).filter((id) => !known.has(id))).toEqual([]);
  });

  it('gives every exception a reason a card can print', () => {
    const silent = Object.entries(NOT_DRAWN).filter(([, why]) => why.trim().length < 10);
    expect(silent).toEqual([]);
  });

  it('asks the catalogue for a component’s id the way the app spells it', () => {
    // `folder/name`, and no platform in it: `media/VideoFrame` is one entry here
    // and two rows in the reference, because the gallery draws whichever half the
    // bundler kept and cannot say which.
    expect(CATALOGUE).toMatch(/export function componentId\(folder: string, name: string\)/);
    expect(REGISTRY).toContain('componentId(folder.folder, entry.name)');
  });

  it('keeps vite-plugin-rnw ahead of uniwind in the plugin list', () => {
    // Swapped, every drawn component loses its `className` and paints nothing:
    // both plugins alias `react-native`, the earlier entry wins the merge, and
    // only `react-native-web` forwards a class name to the DOM where the app's
    // stylesheet can reach it. Measured on 2026-09-11 — `Card` came out as a bare
    // `css-g5y9jx` with no ground, no border and no hairline. `vite build` is
    // green either way, `scripts/measure-direct.mjs` reports 47 of 47 either way,
    // and the page renders either way. Nothing but a pair of eyes sees it, which
    // is why the order is asserted here. `vite.app.mjs` carries the table.
    const plugins = /export function appPlugins\(\) \{[\s\S]*?\n\}/.exec(RECIPE)?.[0] ?? '';
    expect(plugins).toMatch(/rnw\(\)[\s\S]*uniwind\(/);
  });

  it('hands the site’s appearance to Uniwind rather than only painting a class', () => {
    // The trap ADR 0027 records and ADR 0008 records the NativeWind version of.
    // A `.dark` class on `<html>` moves the CSS variables and leaves
    // `useUniwind().theme` at light, so every colour a component reads in
    // TypeScript — `useColors()`, and therefore every `<Typo>` — stays on the
    // light value over a dark ground. Measured: `canvas` at `#1a1a1a` under text
    // at `#333`. Nothing about the page looks broken to a build.
    expect(PREVIEW).toMatch(/Uniwind\.setTheme\(/);
  });

  it('puts a store and a safe area above every specimen', () => {
    // Measured on 2026-09-11 by drawing all 45 entries with neither: `MiniPlayer`
    // and everything else that selects from a slice threw, because react-redux
    // refuses rather than degrading without a Provider, and `LoginGate`,
    // `RecoveryScreen`, `Screen`, `ScreenHeader` and `SafeAreaView` threw on
    // `useSafeAreaInsets`, which refuses rather than defaulting. Both are
    // one-line providers and neither is a stub: the store is `apps/mobile`'s own
    // instance, and the insets are zero because a page has no notch.
    expect(PREVIEW).toMatch(/<Provider store=\{coreStore\}>/);
    expect(PREVIEW).toMatch(/<SafeAreaProvider initialMetrics=/);
  });
});

/**
 * The overview's cards, and the one thing about them that is a decision.
 *
 * `/components` carried a Draw button on every card for one commit, inherited
 * from the era when a preview meant booting the whole app in an iframe and
 * mounting one cost an app boot. It costs a React mount now: `direct.tsx` imports
 * the components statically, so the bytes are paid on arrival whether or not
 * anybody presses anything, and all 47 together were measured at about 100 ms of
 * the first render, 460 ms on a CPU throttled four times, with no frame over
 * 17 ms while scrolling the page end to end. A control that gates nothing
 * misrepresents what it costs to look, so there is none, and this is the check
 * that keeps one from coming back by habit. ADR 0028 carries the numbers.
 *
 * Read as text for the same reason the registry is: asking whether a page mounts
 * something on arrival by rendering it would need the app's whole toolchain,
 * `react-native-web` and a DOM, to answer a question about a branch.
 */
describe('the components overview', () => {
  const PAGE = readFileSync(join(HANDBOOK, 'src/pages/Components.tsx'), 'utf8');

  it('draws every card’s specimen on arrival, with nothing to press', () => {
    expect(PAGE).toContain('<DirectPreview');
    // No control of any kind on a card: the grid's only interactive parts are
    // links, and the filter and the segment above it, which are the shell's.
    expect(PAGE).not.toMatch(/onClick|onDraw|\bPlay\b/);
  });

  it('reserves the preview area’s height rather than letting a specimen set it', () => {
    // 47 specimens settle at their own speeds. A preview area sized by its
    // content would reflow the grid under a reader who was already reading it,
    // which is the failure the button used to hide by never drawing at all.
    expect(PAGE).toMatch(/className="stage-grid relative h-\[11rem\] shrink-0/);
  });

  it('keeps the state a component this site cannot draw explains itself in', () => {
    // `NOT_DRAWN` is empty today. It is the branch a future exception arrives
    // through, and deleting it because nothing uses it is how the next exception
    // ends up drawn as a blank card instead of a sentence.
    expect(PAGE).toContain('NOT_DRAWN[id]');
    expect(PAGE).toContain('entry === undefined');
  });
});
