import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { ROOT } from '../plugin/collect.ts';
import { NOT_DRAWN } from '../src/components/direct-ids.ts';
import { appPlugins } from '../vite.app.mjs';

const HANDBOOK = join(ROOT, 'apps/handbook');
const API = join(HANDBOOK, 'content/api.generated.json');
const REGISTRY = readFileSync(join(HANDBOOK, 'src/components/direct.tsx'), 'utf8');
const PREVIEW = readFileSync(join(HANDBOOK, 'src/components/DirectPreview.tsx'), 'utf8');
const CATALOGUE = readFileSync(join(ROOT, 'apps/mobile/src/gallery/catalogue.tsx'), 'utf8');

/**
 * What the handbook draws itself, held against what the app actually has.
 *
 * `direct-ids.ts` is imported and `direct.tsx` is read as text, which is the
 * split the whole file turns on: the exceptions are plain data, the registry is
 * over React Native components, and a test that imported the second would need
 * the app's entire toolchain to answer a question about strings.
 *
 * How many components *build* is not asserted anywhere, and that is deliberate:
 * `scripts/measure-direct.mjs` answers it, the answer moves when react-native,
 * expo or Rolldown move, and a check that reddens for an upstream release gets
 * switched off. What is asserted here is what this repository owns.
 */
describe('the components the handbook draws', () => {
  /**
   * The roster is the app's, and this is the fact that makes the rest of the
   * file short.
   *
   * ADR 0027 shipped two entries typed out by hand. ADR 0028 replaced them with
   * `apps/mobile/src/gallery/catalogue.tsx`, which already says what every
   * component is shown with, in the props' own words, and which the app's own
   * `__tests__/gallery-catalogue.test.ts` fails on when a component is missing.
   * A second list here would be the two copies AGENTS.md exists to prevent, and
   * it would be the copy nobody edits.
   */
  it('takes its specimens from the app’s own catalogue rather than copying them', () => {
    expect(REGISTRY).toMatch(/from '@\/gallery\/catalogue'/);
    // A specimen written here would be a second answer to "what does this
    // component look like", which is exactly what the import is for.
    expect(REGISTRY).not.toContain('specimens: [');
  });

  it('names only components the app really has, as its exceptions', () => {
    if (!existsSync(API)) {
      // Generated by `npm run api`, which the build runs first and which a fresh
      // clone has not run. Green on a developer's machine and red in CI is worse
      // than skipped in both.
      console.log('skipped: content/api.generated.json is not built');
      return;
    }
    const api = JSON.parse(readFileSync(API, 'utf8')) as {
      components: { groups: { name: string; components: { name: string }[] }[] };
    };
    const known = new Set(
      api.components.groups.flatMap((group) =>
        group.components.map((component) => `${group.name}/${component.name}`),
      ),
    );

    expect(Object.keys(NOT_DRAWN).filter((id) => !known.has(id))).toEqual([]);
  });

  it('gives every exception a reason a card can print', () => {
    const silent = Object.entries(NOT_DRAWN).filter(([, why]) => why.trim().length < 10);
    expect(silent).toEqual([]);
  });

  it('asks the catalogue for a component’s id the way the app spells it', () => {
    // `folder/name`, and no platform in it: `media/VideoFrame` is one entry here
    // and two rows in the reference, because the gallery draws whichever half the
    // bundler kept and cannot say which.
    expect(CATALOGUE).toMatch(/export function componentId\(folder: string, name: string\)/);
    expect(REGISTRY).toContain('componentId(folder.folder, entry.name)');
  });

  it('keeps vite-plugin-rnw ahead of uniwind in the plugin list', () => {
    // Swapped, every drawn component loses its `className` and paints nothing:
    // both plugins alias `react-native`, the earlier entry wins the merge, and
    // only `react-native-web` forwards a class name to the DOM where the app's
    // stylesheet can reach it. Measured on 2026-09-11 — `Card` came out as a bare
    // `css-g5y9jx` with no ground, no border and no hairline. `vite build` is
    // green either way, `scripts/measure-direct.mjs` reports 47 of 47 either way,
    // and the page renders either way. Nothing but a pair of eyes sees it, which
    // is why the order is asserted here. `vite.app.mjs` carries the table.
    //
    // The built list and not the file's text: `rnw()` expands to nine plugins and
    // the one that does the aliasing is `vite:react-native-web-babel`, so what has
    // to come first is a fact about the array rather than about the order two
    // calls happen to be written in.
    const names = appPlugins()
      .flat(Infinity)
      .map((plugin) => (plugin as { name?: string } | null)?.name);
    expect(names).toContain('vite:react-native-web-babel');
    expect(names).toContain('uniwind');
    expect(names.indexOf('vite:react-native-web-babel')).toBeLessThan(names.indexOf('uniwind'));
  });

  it('lays a specimen out the way the app lays it out', () => {
    // The stage boxes are `View`s and not `<div>`s, and the difference is not
    // cosmetic: a view is a flex column that stretches its children, a `<div>` is
    // a block box that does neither, and a component's outermost element is laid
    // out by its parent. Measured on 2026-09-11 with divs: `ui/Badge` and
    // `participate/ClaimStatusTag` ran the full width of the column although both
    // say `self-start`, because `align-self` means nothing to a child of a block
    // box, and `ui/Chip` hugged its label where the app stretches it.
    expect(PREVIEW).toMatch(/from 'react-native'/);
    expect(PREVIEW).not.toMatch(/<div className="p-s"/);
  });

  // What is above a specimen — the stylesheet, the fonts, the store, the safe
  // area, the gesture root and the appearance — is the app's own environment and
  // is asserted in `environment.test.ts`, which is also where the reason it is
  // not a list in this package is written down.
});

/**
 * The overview's cards, and the one thing about them that is a decision.
 *
 * `/components` carried a Draw button on every card for one commit, inherited
 * from the era when a preview meant booting the whole app in an iframe and
 * mounting one cost an app boot. It costs a React mount now: `direct.tsx` imports
 * the components statically, so the bytes are paid on arrival whether or not
 * anybody presses anything, and all 47 together were measured at about 100 ms of
 * the first render, 460 ms on a CPU throttled four times, with no frame over
 * 17 ms while scrolling the page end to end. A control that gates nothing
 * misrepresents what it costs to look, so there is none, and this is the check
 * that keeps one from coming back by habit. ADR 0028 carries the numbers.
 *
 * Read as text for the same reason the registry is: asking whether a page mounts
 * something on arrival by rendering it would need the app's whole toolchain,
 * `react-native-web` and a DOM, to answer a question about a branch.
 */
describe('the components overview', () => {
  const PAGE = readFileSync(join(HANDBOOK, 'src/pages/Components.tsx'), 'utf8');

  it('draws every card’s specimen on arrival, with nothing to press', () => {
    expect(PAGE).toContain('<DirectPreview');
    // No control of any kind on a card: the grid's only interactive parts are
    // links, and the filter and the segment above it, which are the shell's.
    expect(PAGE).not.toMatch(/onClick|onDraw|\bPlay\b/);
  });

  it('reserves the preview area rather than letting a specimen set it', () => {
    // 47 specimens settle at their own speeds. A preview area sized by its
    // content would reflow the grid under a reader who was already reading it,
    // which is the failure the button used to hide by never drawing at all.
    //
    // A square derived from the column, and not the `h-[11rem]` this shipped
    // with: a reserved height in rem is a number that has to be kept in step with
    // the grid by hand, and it was 176px against columns of 260, 379 and 432 at
    // three different widths. `aspect-ratio: 1` reserves the same box without
    // stating a size, so the two cannot part.
    expect(PAGE).toMatch(/aspect-square/);
    expect(PAGE).not.toMatch(/h-\[\d/);
  });

  it('centres a short specimen with auto margins, so a tall one keeps its top', () => {
    // The whole of the rule, and it is one class. Auto margins take free space
    // when there is some and resolve to zero when there is none, so a row that
    // does not fill the square is centred in it and a component taller than the
    // square is drawn from its top edge and cut off at the bottom.
    // `justify-content: center` would split the overflow between both edges and
    // shave the top off every tall component, which is the half a reader most
    // needs — a screen's header, a card's title.
    expect(PAGE).toContain('my-auto');
    // And the column itself stays full width. Shrink-wrapping it would centre
    // `ui/Badge` and `participate/ClaimStatusTag`, which both say `self-start` in
    // the app, and hide which components stretch and which hug.
    expect(PAGE).toContain('mx-auto my-auto w-full');
  });

  it('asks the two boxes which cards clip rather than naming the components', () => {
    // The set changes with the column the grid gives a card, with the window and
    // with the app; measured on 2026-09-11, the same specimens clip nine times in
    // a 277px column and three times in a 340px one. A list in this repository
    // would be a card cropping a component while claiming to show all of it,
    // which is what the iframes were taken off this page for (ADR 0027).
    const clipped = readFileSync(join(HANDBOOK, 'src/components/clipped.ts'), 'utf8');
    expect(clipped).toContain('ResizeObserver');
    // The marker is drawn from the answer the two boxes give, and from nothing
    // else: no set, no list, no id in a condition anywhere.
    expect(PAGE).toContain('useClipped');
    expect(PAGE).toContain('{clipped && (');
    // And the decision itself knows no component at all — it is two numbers.
    for (const name of ['RecoveryScreen', 'LoginGate', 'ArticleHero', 'NOT_DRAWN']) {
      expect(clipped).not.toContain(name);
    }
  });

  it('lets the grid decide the column, between a floor and a ceiling', () => {
    // The square is the column, so the grid is where its size is decided. A band
    // rather than breakpoints, because the column is not a function of the window
    // here: the right-hand panel takes a quarter of it, and `sm:grid-cols-2
    // xl:grid-cols-3` gave 260px at 640, 379px at 1280 and 432px at 1440.
    // `auto-fit` and not `auto-fill` would stretch a one-component folder's
    // single card across the whole row, so its square would be twice the one
    // above it; the class, not the prose, is where that is settled.
    expect(PAGE).toMatch(/grid-cols-\[repeat\(auto-fill,minmax\(min\(100%,\d+rem\),1fr\)\)\]/);
    // The ceiling is on the card and not in the track, and that is not a style
    // choice: `repeat()` counts an `auto-fill` with a definite maximum AT that
    // maximum, so putting both ends in the track fits two 24rem columns at 1280
    // where three 19rem ones fit, and loses a column to say the same thing.
    expect(PAGE).toMatch(/max-w-\[\d+rem\]/);
  });

  it('keeps the state a component this site cannot draw explains itself in', () => {
    // `NOT_DRAWN` is empty today. It is the branch a future exception arrives
    // through, and deleting it because nothing uses it is how the next exception
    // ends up drawn as a blank card instead of a sentence.
    expect(PAGE).toContain('NOT_DRAWN[id]');
    expect(PAGE).toContain('entry === undefined');
  });

  it('takes the setting from where the site stores it, never off the root element', () => {
    // The second half of the same trap, and the more expensive one, because it
    // passes all four appearance combinations. `setTheme('system')` resolves the
    // device scheme once and stamps the answer back onto `<html>`; reading the
    // class therefore reads Uniwind's own output, hands it back as an explicit
    // theme, and pins the WHOLE SITE to the scheme the device had at load. Measured
    // on the built site on 2026-09-11: with the setting on System and the device
    // switched to dark afterwards, `/` and `/architecture` went dark and
    // `/components` stayed white. `theme.ts` owns the stored setting and nothing
    // else writes it, which is the only reading that cannot be Uniwind's.
    expect(PREVIEW).toMatch(/storedAppearance\(/);
    expect(PREVIEW).not.toMatch(/documentElement\.classList/);
  });
});
