/**
 * Builds this app's offline bundle — the feed snapshots and pre-extracted articles
 * that make the demo path (Home → read an article) work without a network.
 *
 *   npm run offline-articles -w @correctiv/mobile-rn
 *
 * Collecting lives in the core (`@correctiv/app-core/articles/offline-bundle`), so
 * only the writing is local: one generated TypeScript module. The extraction
 * backend is the DOM one, the same one this app uses at runtime, so the bundle
 * cannot differ from what the app would have extracted
 * live.
 *
 * The snapshots matter most on the web target, where they are not a fallback for a
 * lost network but the only way articles appear at all: correctiv.org sends no
 * `Access-Control-Allow-Origin`, so a browser blocks every feed request. See
 * `TROUBLESHOOTING.md` → The web target.
 *
 * Cover images are bundled alongside, downscaled and inlined as data URIs. Without
 * them an offline Home is a list of grey rectangles — the feed items keep the
 * remote URLs they were fetched with, and none of those load. Needs ImageMagick;
 * without it the covers are skipped and the app falls back to the remote URLs.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { extractArticleFromDom } from '@correctiv/app-core/articles/extract/dom';
import { collectOfflineBundle } from '@correctiv/app-core/articles/offline-bundle';
import type { Article } from '@correctiv/app-core/articles/types';
import type { FeedItem, FeedKey } from '@correctiv/app-core/types/models';

const ARTICLES_DIR = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'lib',
  'articles',
);
const OUT = resolve(ARTICLES_DIR, 'offlineBundle.generated.ts');
const COVERS_OUT = resolve(ARTICLES_DIR, 'offlineCovers.generated.ts');

/**
 * Cover width in pixels. The hero is the widest use — a 402pt phone at 2× asks for
 * ~800px — but this is the *offline* copy, so it buys legibility rather than
 * sharpness: every pixel here is base64 in the JS bundle, and 640 keeps all fifteen
 * covers under a third of a megabyte.
 */
const COVER_WIDTH = 640;
const COVER_QUALITY = 68;

const UA =
  'Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 Chrome/124 Mobile Safari/537.36';

const PICK: Partial<Record<FeedKey, number>> = {
  recherchen: 5,
  faktencheck: 5,
  klima: 3,
  schweiz: 2,
};

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return res.text();
}

/** True if ImageMagick is callable — without it the covers are simply left out. */
function hasImageMagick(): boolean {
  try {
    execFileSync('magick', ['-version'], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

/**
 * Downloads one cover and returns it as a downscaled WebP data URI.
 *
 * `magick - webp:-` pipes through stdin/stdout, so nothing is written to disk: the
 * bundle is a generated module, not an asset folder, and a stray temp file that
 * outlives a failed run would be committed by the next person who runs `git add`.
 */
async function inlineCover(url: string): Promise<string | null> {
  try {
    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!res.ok) return null;
    const webp = execFileSync(
      'magick',
      ['-', '-resize', `${COVER_WIDTH}x`, '-strip', '-quality', String(COVER_QUALITY), 'webp:-'],
      { input: Buffer.from(await res.arrayBuffer()), maxBuffer: 64 * 1024 * 1024 },
    );
    return `data:image/webp;base64,${webp.toString('base64')}`;
  } catch {
    return null; // a cover image is a nicety; the article still reads
  }
}

const bundle = await collectOfflineBundle({
  fetchText,
  extract: extractArticleFromDom,
  plan: { pick: PICK },
  onProgress: (message) => console.log(message),
});

const articles: Record<string, Article> = {};
for (const { article } of bundle.articles) articles[article.url] = article;

const feeds: Partial<Record<FeedKey, FeedItem[]>> = {};
for (const { key, items } of bundle.snapshots) feeds[key] = items;

const header =
  '// AUTO-GENERATED by scripts/fetch-offline-articles.mts — do not edit by hand.\n' +
  '// The bundled offline content: feed snapshots and pre-extracted articles, served\n' +
  '// to the core through the ContentBundle port in lib/platform/expo.ts.\n' +
  '// Regenerate: npm run offline-articles\n' +
  '/* eslint-disable */\n' +
  "import type { Article } from '@correctiv/app-core/articles/types';\n" +
  "import type { FeedItem, FeedKey } from '@correctiv/app-core/types/models';\n\n";

// Snapshots are indented one space, articles two: the snapshots are the bulk of
// this file and every level costs the web bundle real bytes.
writeFileSync(
  OUT,
  header +
    `export const OFFLINE_FEEDS: Partial<Record<FeedKey, FeedItem[]>> = ${JSON.stringify(feeds, null, 1)};\n\n` +
    `export const OFFLINE_ARTICLES: Record<string, Article> = ${JSON.stringify(articles, null, 2)};\n`,
);

const covers: Record<string, string> = {};
if (hasImageMagick()) {
  for (const { article } of bundle.articles) {
    if (!article.heroImageUrl) continue;
    const inlined = await inlineCover(article.heroImageUrl);
    if (inlined) covers[article.url] = inlined;
  }
  console.log(`\n${Object.keys(covers).length} covers inlined at ${COVER_WIDTH}px`);
} else {
  console.warn('\n! ImageMagick not found — no covers bundled. Offline lists stay grey.');
}

writeFileSync(
  COVERS_OUT,
  '// AUTO-GENERATED by scripts/fetch-offline-articles.mts — do not edit by hand.\n' +
    `// Article covers, downscaled to ${COVER_WIDTH}px WebP and inlined as data URIs. The\n` +
    '// ContentBundle port hands them to the core, which swaps them in for the remote\n' +
    '// URLs a stale feed item still carries (stores/feeds.ts → adoptBundledImages).\n' +
    '// Regenerate: npm run offline-articles\n' +
    '/* eslint-disable */\n\n' +
    `export const OFFLINE_COVERS: Record<string, string> = ${JSON.stringify(covers, null, 1)};\n`,
);

const items = Object.values(feeds).reduce((n, list) => n + list.length, 0);
console.log(
  `\n${Object.keys(articles).length} articles and ${items} feed items ` +
    `in ${Object.keys(feeds).length} snapshots → offlineBundle.generated.ts ` +
    `(${Math.round(Buffer.byteLength(JSON.stringify(feeds)) / 1024)} kB of snapshots), ` +
    `${Object.keys(covers).length} covers → offlineCovers.generated.ts ` +
    `(${Math.round(Buffer.byteLength(JSON.stringify(covers)) / 1024)} kB)`,
);
