/**
 * Builds this app's offline article bundle — the pre-extracted articles that make
 * the demo path (Home → read an article) work without a network.
 *
 *   npm run offline-articles -w @correctiv/mobile-rn
 *
 * Collecting is shared with the NativeScript app
 * (`@correctiv/app-core/articles/offline-bundle`); what differs is only the
 * writing — one generated TypeScript module here, JSON files in an app folder
 * there. The extraction backend is the DOM one, the same one this app uses at
 * runtime, so the bundle cannot differ from what the app would have extracted
 * live.
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { extractArticleFromDom } from '@correctiv/app-core/articles/extract/dom';
import { collectOfflineBundle } from '@correctiv/app-core/articles/offline-bundle';
import type { Article } from '@correctiv/app-core/articles/types';
import type { FeedKey } from '@correctiv/app-core/types/models';

const OUT = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'lib',
  'articles',
  'offlineArticles.generated.ts',
);

const UA =
  'Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 Chrome/124 Mobile Safari/537.36';

const PICK: Partial<Record<FeedKey, number>> = {
  recherchen: 5,
  faktencheck: 5,
  klima: 3,
  schweiz: 2,
};

async function fetchText(url: string): Promise<string> {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return res.text();
}

const bundle = await collectOfflineBundle({
  fetchText,
  extract: extractArticleFromDom,
  plan: { pick: PICK },
  onProgress: (message) => console.log(message),
});

const articles: Record<string, Article> = {};
for (const { article } of bundle.articles) articles[article.url] = article;

const header =
  '// AUTO-GENERATED by scripts/fetch-offline-articles.ts — do not edit by hand.\n' +
  '// Bundled, pre-extracted articles: the offline path for the demo, served to the\n' +
  '// core through the ContentBundle port in lib/platform/expo.ts.\n' +
  '// Regenerate: npm run offline-articles\n' +
  '/* eslint-disable */\n' +
  "import type { Article } from '@correctiv/app-core/articles/types';\n\n";

writeFileSync(
  OUT,
  `${header}export const OFFLINE_ARTICLES: Record<string, Article> = ${JSON.stringify(articles, null, 2)};\n`,
);
console.log(`\n${Object.keys(articles).length} articles bundled → offlineArticles.generated.ts`);
