/**
 * Snapshots each curated Salon5 show (metadata + newest episodes) into a generated
 * TypeScript module, which the `ContentBundle` port serves when a show is
 * unreachable. Episode audio stays a remote MP3 URL — only the list is bundled.
 *
 *   npm run offline-podcasts -w @correctiv/mobile-rn
 *
 * It calls the core's `fetchPodcastSeries`, the same function the app calls, so the
 * snapshot cannot drift from the live shape.
 *
 * Without this, the Mediathek's cascade skips the bundle and lands on the four-show
 * sample seed in `data/podcasts.ts`, which is why the web target used to print
 * "Ohne Verbindung — Sie sehen Beispielfolgen." on every visit: a browser cannot
 * reach Castopod either (no CORS header), so the bundle is not a fallback there but
 * the only real data the Mediathek ever gets.
 *
 * A show that fails keeps its previous snapshot rather than disappearing from the
 * bundle — one unreachable feed must not silently shrink the offline library.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { PODCAST_CHANNELS } from '@correctiv/app-core/data/feeds.config';
import type { PodcastSeries } from '@correctiv/app-core/data/podcasts';
import { fetchPodcastSeries } from '@correctiv/app-core/services/podcast.service';

const OUT = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'lib',
  'podcasts',
  'offlineBundle.generated.ts',
);

/** The snapshot that is already committed, so a failed show keeps its episodes. */
function previous(): Record<string, PodcastSeries> {
  try {
    const source = readFileSync(OUT, 'utf8');
    const json = source.slice(source.indexOf('= {') + 2, source.lastIndexOf('};') + 1);
    return JSON.parse(json) as Record<string, PodcastSeries>;
  } catch {
    return {};
  }
}

const kept = previous();
const series: Record<string, PodcastSeries> = {};
let live = 0;

for (const handle of PODCAST_CHANNELS) {
  process.stdout.write(`Podcast ${handle} … `);
  try {
    const show = await fetchPodcastSeries(handle);
    series[handle] = show;
    live += 1;
    console.log(`✓ ${show.title} (${show.episodes.length} episodes)`);
  } catch (err) {
    const fallback = kept[handle];
    if (fallback) series[handle] = fallback;
    console.warn(
      `! ${(err as Error).message}${fallback ? ' — keeping the previous snapshot' : ''}`,
    );
  }
}

if (Object.keys(series).length === 0) {
  console.error('\nNo show could be snapshotted and none was committed — writing nothing.');
  process.exit(1);
}

const header =
  '// AUTO-GENERATED by scripts/fetch-offline-podcasts.mts — do not edit by hand.\n' +
  '// Bundled Salon5 podcast snapshots, served to the core through the ContentBundle\n' +
  '// port in lib/platform/expo.ts. Episode audio stays remote; only the lists are here.\n' +
  '// Regenerate: npm run offline-podcasts\n' +
  '/* eslint-disable */\n' +
  "import type { PodcastSeries } from '@correctiv/app-core/data/podcasts';\n\n";

writeFileSync(
  OUT,
  header +
    `export const OFFLINE_PODCASTS: Record<string, PodcastSeries> = ${JSON.stringify(series, null, 1)};\n`,
);

const episodes = Object.values(series).reduce((n, show) => n + show.episodes.length, 0);
console.log(
  `\n${Object.keys(series).length} shows (${live} live) and ${episodes} episodes ` +
    `→ offlineBundle.generated.ts ` +
    `(${Math.round(Buffer.byteLength(JSON.stringify(series)) / 1024)} kB)`,
);
