import { ApplicationSettings, File, Folder, knownFolders, path } from '@nativescript/core';
import type { BlobStore, ContentBundle, CorePlatform, KeyValueStore } from '@correctiv/app-core';
import type { Article } from '@correctiv/app-core/articles/types';
import type { PodcastSeries } from '@correctiv/app-core/data/podcasts';
import type { FeedItem, FeedKey } from '@correctiv/app-core/types/models';

import { nativeScriptAudio } from '../services/audio.service';

/**
 * The NativeScript host's half of `@correctiv/app-core`'s platform ports — the
 * ONLY place in this app where the core's needs meet the NativeScript SDK.
 * Everything here is one of the four interfaces in `ports/index.ts`.
 */

const keyValue: KeyValueStore = {
  getString(key) {
    const raw = ApplicationSettings.getString(key, '');
    return raw === '' ? null : raw;
  },
  setString(key, value) {
    ApplicationSettings.setString(key, value);
  },
  remove(key) {
    ApplicationSettings.remove(key);
  },
};

function cacheFolder(namespace: string): Folder {
  return knownFolders.documents().getFolder(`cache/${namespace}`);
}

/**
 * `File` is synchronous here and the port is async — deliberately. The port is
 * shaped for the slower host (AsyncStorage on Expo, IndexedDB in a browser);
 * resolving an already-finished read costs a microtask and buys one cache
 * implementation instead of two.
 */
const blobs: BlobStore = {
  read(namespace, name) {
    try {
      const filePath = path.join(cacheFolder(namespace).path, name);
      if (!File.exists(filePath)) return Promise.resolve(null);
      return Promise.resolve(File.fromPath(filePath).readTextSync());
    } catch {
      return Promise.resolve(null);
    }
  },
  write(namespace, name, contents) {
    try {
      cacheFolder(namespace).getFile(name).writeTextSync(contents);
    } catch {
      // the blob cache is best-effort; never let it break a render
    }
    return Promise.resolve();
  },
};

// --- the bundled offline content ---------------------------------------------

function appPath(...segments: string[]): string {
  return path.join(knownFolders.currentApp().path, ...segments);
}

/** Reads and parses a bundled JSON asset, or null. Every caller treats it as optional. */
function readJson<T>(...segments: string[]): T | null {
  try {
    const file = appPath(...segments);
    if (!File.exists(file)) return null;
    return JSON.parse(File.fromPath(file).readTextSync()) as T;
  } catch {
    return null;
  }
}

interface OfflineIndexEntry {
  slug: string;
  url: string;
  localImage: string | null;
}

/**
 * The article index, read once. It maps a URL to the bundled file that holds it
 * and to the cover image downloaded alongside — both generated by
 * `scripts/fetch-offline-articles.ts`.
 */
let articleIndex: Map<string, OfflineIndexEntry> | null = null;

function index(): Map<string, OfflineIndexEntry> {
  if (articleIndex) return articleIndex;
  const parsed = readJson<{ articles: OfflineIndexEntry[] }>(
    'assets',
    'data',
    'articles',
    'index.json',
  );
  articleIndex = new Map((parsed?.articles ?? []).map((entry) => [entry.url, entry]));
  return articleIndex;
}

const content: ContentBundle = {
  feed(key: FeedKey) {
    return readJson<FeedItem[]>('assets', 'data', 'feeds', `${key}.json`);
  },
  article(url) {
    const entry = index().get(url);
    if (!entry) return null;
    const article = readJson<Article>('assets', 'data', 'articles', `${entry.slug}.json`);
    return article ? { ...article, offline: true } : null;
  },
  image(url) {
    return index().get(url)?.localImage ?? null;
  },
  podcastSeries(id) {
    return readJson<PodcastSeries>('assets', 'data', 'podcasts', `${id}.json`);
  },
};

export const nativeScriptPlatform: CorePlatform = {
  keyValue,
  blobs,
  content,
  audio: nativeScriptAudio,
};
