// AUTO-GENERATED by scripts/fetch-offline-podcasts.mts — do not edit by hand.
// Bundled Salon5 podcast snapshots, served to the core through the ContentBundle
// port in lib/platform/expo.ts. Episode audio stays remote; only the lists are here.
// Regenerate: npm run offline-podcasts
/* eslint-disable */
import type { PodcastSeries } from '@correctiv/app-core/data/podcasts';

export const OFFLINE_PODCASTS: Record<string, PodcastSeries> = {
 "pausenbrot": {
  "id": "pausenbrot",
  "title": "Pausenbrot",
  "publisher": "Salon5",
  "description": "Gruppenzwang, Lernstress, Mobbing und Leistungsdruck: Wir sprechen in dieser Podcast-Serie über alles rund um Schule, Uni und Arbeit. Wie kann ich am besten für die nächste Klassenarbeit lernen? Warum ist das Bildungssystem in Deutschland…",
  "imageUrl": "https://salon5.correctiv.net/media/podcasts/pausenbrot/cover_feed.png",
  "episodes": [
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/kein-deutschland-ticket-mehr",
    "title": "Kein Deutschland-Ticket mehr?!",
    "date": "2026-07-22T10:43:50.000Z",
    "durationLabel": "8 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/kein-deutschland-ticket-mehr.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/woher-kommt-gewalt-an-schulen",
    "title": "Woher kommt Gewalt an Schulen?",
    "date": "2026-07-20T14:33:58.000Z",
    "durationLabel": "36 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/woher-kommt-gewalt-an-schulen.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/regelungen-fur-sommerferienzeiten",
    "title": "Regelungen für Sommerferienzeiten",
    "date": "2026-07-17T09:06:01.000Z",
    "durationLabel": "4 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/regelungen-fur-sommerferienzeiten.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/angst-vorm-zeugnis",
    "title": "Angst vorm Zeugnis?",
    "date": "2026-07-15T10:19:05.000Z",
    "durationLabel": "21 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/angst-vorm-zeugnis.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/kostenlose-sommerferien-aktivitaten-in-koln-und-essen",
    "title": "Kostenlose Sommerferien Aktivitäten in Köln und Essen",
    "date": "2026-07-13T10:21:14.000Z",
    "durationLabel": "26 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/kostenlose-sommerferien-aktivitaten-in-koln-und-essen.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/auslandsaufenthalt-in-sudafrika",
    "title": "Auslandsaufenthalt in Südafrika",
    "date": "2026-06-19T09:29:21.000Z",
    "durationLabel": "48 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/auslandsaufenthalt-in-sudafrika.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/gott-mit-dir-du-land-der-bayern",
    "title": "Gott mit dir, du Land der Bayern",
    "date": "2026-06-08T22:01:00.000Z",
    "durationLabel": "25 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/gott-mit-dir-du-land-der-bayern.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/so-geht-schule-in-anderen-landern",
    "title": "So geht Schule in anderen Ländern",
    "date": "2026-05-14T22:01:00.000Z",
    "durationLabel": "5 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/so-geht-schule-in-anderen-landern.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/jedes-abitur-ist-gleich-oder",
    "title": "Jedes Abitur ist gleich… oder?",
    "date": "2026-04-29T10:57:39.000Z",
    "durationLabel": "20 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/jedes-abitur-ist-gleich-oder.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/wie-nutzen-lehrer-ihre-macht-aus",
    "title": "Wie nutzen Lehrer ihre Macht aus?",
    "date": "2026-04-20T06:00:00.000Z",
    "durationLabel": "16 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/wie-nutzen-lehrer-ihre-macht-aus.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/schule-lernen-furs-leben-oder-oft-unnotig",
    "title": "Schule: Lernen fürs Leben oder oft unnötig?",
    "date": "2026-04-16T07:41:44.000Z",
    "durationLabel": "32 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/schule-lernen-furs-leben-oder-oft-unnotig.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/erste-hilfe-als-fach-in-der-schule-ist-das-sinnvoll",
    "title": "Erste Hilfe als Fach in der Schule: Ist das sinnvoll?",
    "date": "2026-03-03T23:01:00.000Z",
    "durationLabel": "13 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/erste-hilfe-als-fach-in-der-schule-ist-das-sinnvoll.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/durfen-schulerzeitungen-zensiert-werden",
    "title": "Dürfen Schülerzeitungen zensiert werden?",
    "date": "2026-02-26T10:22:24.000Z",
    "durationLabel": "23 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/durfen-schulerzeitungen-zensiert-werden.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/interview-herr-schmelzer-mussen-lehrer-neutral-sein",
    "title": "Interview: Herr Schmelzer, müssen Lehrer neutral sein?",
    "date": "2026-02-23T09:38:03.000Z",
    "durationLabel": "13 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/interview-herr-schmelzer-mussen-lehrer-neutral-sein.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/von-peru-nach-deutschland",
    "title": "Von Peru nach Deutschland",
    "date": "2026-01-28T16:00:59.000Z",
    "durationLabel": "13 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/von-peru-nach-deutschland.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/die-schlimmsten-aussagen-von-lehrkraften",
    "title": "Die schlimmsten Aussagen von Lehrkräften!",
    "date": "2026-01-12T23:01:00.000Z",
    "durationLabel": "38 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/die-schlimmsten-aussagen-von-lehrkraften.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/kurz-erklart-welche-rechte-und-pflichten-haben-lehrer",
    "title": "Kurz erklärt: Welche Rechte und Pflichten haben Lehrer?",
    "date": "2026-01-11T23:01:00.000Z",
    "durationLabel": "4 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/kurz-erklart-welche-rechte-und-pflichten-haben-lehrer.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/sechs-wochen-in-peru-so-war-malins-schuleraustausch",
    "title": "Sechs Wochen in Peru: So war Malins Schüleraustausch",
    "date": "2025-12-09T09:42:10.000Z",
    "durationLabel": "22 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/sechs-wochen-in-peru-so-war-malins-schuleraustausch.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/bundesschulerkonferenz-zum-iqb-bildungstrend",
    "title": "Bundesschülerkonferenz zum IQB-Bildungstrend",
    "date": "2025-10-24T23:00:00.000Z",
    "durationLabel": "27 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/bundesschulerkonferenz-zum-iqb-bildungstrend.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pausenbrot/episodes/digitalisierung-an-schulen-woran-scheiterts",
    "title": "Digitalisierung an Schulen: Woran scheitert’s?",
    "date": "2025-10-17T22:01:00.000Z",
    "durationLabel": "22 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pausenbrot/digitalisierung-an-schulen-woran-scheiterts.mp3"
   }
  ]
 },
 "klima": {
  "id": "klima",
  "title": "Mission Klima",
  "publisher": "Salon5",
  "description": "Klima ist nicht nur Fridays for Future. Sondern auch shoppen, Burger essen und in den Urlaub fahren. Es ist ein Thema, das uns alle betrifft. In dieser Podcast-Serie erfahrt ihr, was der Klimawandel ist und warum er jeden Teil unseres Allt…",
  "imageUrl": "https://salon5.correctiv.net/media/podcasts/klima/cover_feed.png",
  "episodes": [
   {
    "id": "https://salon5.correctiv.net/@klima/episodes/so-denken-jugendliche-uber-den-klimawandel",
    "title": "So denken Jugendliche über den Klimawandel",
    "date": "2026-07-31T12:28:40.000Z",
    "durationLabel": "1 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/so-denken-jugendliche-uber-den-klimawandel.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@klima/episodes/nachhaltigkeit-warum-junge-stimmen-zahlen",
    "title": "Nachhaltigkeit: Warum junge Stimmen zählen",
    "date": "2026-07-29T23:00:00.000Z",
    "durationLabel": "12 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/nachhaltigkeit-warum-junge-stimmen-zahlen.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@klima/episodes/was-den-nationalpark-jasmund-so-besonders-macht",
    "title": "Was den Nationalpark Jasmund so besonders macht",
    "date": "2026-07-29T08:37:46.000Z",
    "durationLabel": "33 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/was-den-nationalpark-jasmund-so-besonders-macht.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@klima/episodes/umwelt-und-klimaschutz-aktiv-mitbestimmen",
    "title": "Umwelt- und Klimaschutz aktiv mitbestimmen",
    "date": "2026-05-22T07:56:34.000Z",
    "durationLabel": "12 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/umwelt-und-klimaschutz-aktiv-mitbestimmen.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@klima/episodes/warum-es-ums-klima-so-still-geworden-ist",
    "title": "Warum es um´s Klima so still geworden ist",
    "date": "2026-03-23T09:26:43.000Z",
    "durationLabel": "14 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/warum-es-ums-klima-so-still-geworden-ist.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@klima/episodes/der-okologische-fus-nein-handabdruck",
    "title": "Der ökologische Fuß-… nein Handabdruck!",
    "date": "2025-11-02T11:35:03.000Z",
    "durationLabel": "29 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/der-okologische-fus-nein-handabdruck.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@klima/episodes/wie-schadlich-ist-fast-fashion-fur-das-klima",
    "title": "Wie schädlich ist Fast Fashion für das Klima?",
    "date": "2025-08-25T09:10:06.000Z",
    "durationLabel": "12 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/wie-schadlich-ist-fast-fashion-fur-das-klima.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@klima/episodes/jugendklimarat-im-gesprach-mit-steffi-blau-von-co2online",
    "title": "Jugendklimarat – Im Gespräch mit Steffi Blau von co2online",
    "date": "2025-07-31T07:00:00.000Z",
    "durationLabel": "17 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/jugendklimarat-im-gesprach-mit-steffi-blau-von-co2online.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@klima/episodes/klimaangst-und-unsere-zukunft",
    "title": "Klimaangst und unsere Zukunft",
    "date": "2025-07-14T07:59:48.000Z",
    "durationLabel": "30 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/klimaangst-und-unsere-zukunft.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@klima/episodes/luisa-neubauer-was-passiert-jetzt-mit-dem-klima",
    "title": "Luisa Neubauer: Was passiert jetzt mit dem Klima?",
    "date": "2025-06-20T07:59:57.000Z",
    "durationLabel": "29 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/luisa-neubauer-was-passiert-jetzt-mit-dem-klima.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@klima/episodes/kurz-erklart-das-plant-friedrich-merz-in-sachen-klima",
    "title": "Kurz erklärt: Das plant Friedrich Merz in Sachen Klima",
    "date": "2025-05-28T22:01:00.000Z",
    "durationLabel": "4 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/kurz-erklart-das-plant-friedrich-merz-in-sachen-klima.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@klima/episodes/kurz-erklart-wie-wird-aus-regen-grundwasser",
    "title": "Kurz Erklärt: Wie wird aus Regen Grundwasser?",
    "date": "2025-05-19T14:05:15.000Z",
    "durationLabel": "6 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/kurz-erklart-wie-wird-aus-regen-grundwasser.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@klima/episodes/zugvogel-und-das-klima-simon-piro-im-interview",
    "title": "Zugvögel und das Klima - Simon Piro im Interview",
    "date": "2025-05-16T12:58:40.000Z",
    "durationLabel": "12 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/zugvogel-und-das-klima-simon-piro-im-interview.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@klima/episodes/saisonstart-wie-nachhaltig-ist-die-formel-1",
    "title": "Saisonstart! Wie nachhaltig ist die Formel 1?",
    "date": "2025-03-14T09:25:23.000Z",
    "durationLabel": "18 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/saisonstart-wie-nachhaltig-ist-die-formel-1.mp3"
   },
   {
    "id": "5faa3b1d-742e-11ef-88b8-a85e453daa56",
    "title": "Kreislaufwirtschaft: Weniger ist mehr!",
    "date": "2025-03-03T14:08:39.000Z",
    "durationLabel": "21 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/kreislaufwirtschaft-weniger-ist-mehr-ijtcm.mp3"
   },
   {
    "id": "586b3ecc-dfb9-11ef-97fe-a85e453daa56",
    "title": "Desinformation rund um die Klima-Krise",
    "date": "2025-01-31T09:54:18.000Z",
    "durationLabel": "11 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/desinformation-rund-um-die-klima-krise-ke5ev.mp3"
   },
   {
    "id": "56f7c88f-8628-11ef-88b8-a85e453daa56",
    "title": "Das Problem der großen Eisschmelze",
    "date": "2024-10-09T10:22:02.000Z",
    "durationLabel": "25 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/das-problem-der-grossen-eisschmelze-m6cdt.mp3"
   },
   {
    "id": "876a2a79-80d7-11ef-88b8-a85e453daa56",
    "title": "Kollaps der Atlantikzirkulation – eine Bedrohung für unser Klima?",
    "date": "2024-10-02T16:01:00.000Z",
    "durationLabel": "19 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/kollaps-der-atlantikzirkulation-eine-bedrohung-fuer-unser-klima-msn3e.mp3"
   },
   {
    "id": "1bcfd68d-80d7-11ef-88b8-a85e453daa56",
    "title": "Was sind eigentlich Klimakipppunkte?",
    "date": "2024-10-02T15:58:00.000Z",
    "durationLabel": "18 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/was-sind-eigentlich-klimakipppunkte-demrq.mp3"
   },
   {
    "id": "b9564007-742e-11ef-88b8-a85e453daa56",
    "title": "Was ist Upcycling?",
    "date": "2024-09-16T13:22:24.000Z",
    "durationLabel": "14 Min.",
    "audio": "https://salon5.correctiv.net/audio/@klima/was-ist-upcycling-l5zoh.mp3"
   }
  ]
 },
 "salon5_erklart": {
  "id": "salon5_erklart",
  "title": "Salon5 erklärt",
  "publisher": "Salon5",
  "description": "Nebenbei einfach ein bisschen schlauer werden? Unsere Salon5 Reporter und Reporterinnen erklären euch komplexe Zusammenhänge, Fachbegriffe und verschaffen euch einen Überblick, über alles, was gerade angeht. So könnt ihr in der Schule nebe…",
  "imageUrl": "https://salon5.correctiv.net/media/podcasts/salon5_erklart/cover_feed.png",
  "episodes": [
   {
    "id": "69ffe3ca-f34e-11ea-a171-a85e453daa56",
    "title": "Kurz erklärt: Systemrelevant",
    "date": "2025-03-03T13:44:59.000Z",
    "durationLabel": "9 Min.",
    "audio": "https://salon5.correctiv.net/audio/@salon5_erklart/kurz-erklaert-systemrelevant-qpl9a.mp3"
   },
   {
    "id": "653fe693-bee2-11eb-9be9-a85e453daa56",
    "title": "Kurz Erklärt: Das Infektionsschutzgesetz",
    "date": "2025-03-03T13:44:49.000Z",
    "durationLabel": "6 Min.",
    "audio": "https://salon5.correctiv.net/audio/@salon5_erklart/kurz-erklaert-das-infektionsschutzgesetz-fop2u.mp3"
   },
   {
    "id": "23610854-19e7-11ec-9be9-a85e453daa56",
    "title": "Kurz Erklärt: Das Wahlprogramm der CDU",
    "date": "2025-03-03T13:44:40.000Z",
    "durationLabel": "5 Min.",
    "audio": "https://salon5.correctiv.net/audio/@salon5_erklart/kurz-erklaert-das-wahlprogramm-der-cdu-vz4hp.mp3"
   },
   {
    "id": "0c322829-1aa6-11ec-9be9-a85e453daa56",
    "title": "Kurz Erklärt: Das Wahlprogramm der Grünen",
    "date": "2025-03-03T13:44:29.000Z",
    "durationLabel": "7 Min.",
    "audio": "https://salon5.correctiv.net/audio/@salon5_erklart/kurz-erklaert-das-wahlprogramm-der-gruenen-paudg.mp3"
   },
   {
    "id": "f5001c94-1b6c-11ec-9be9-a85e453daa56",
    "title": "Kurz Erklärt: Das Wahlprogramm der SPD",
    "date": "2025-03-03T13:44:12.000Z",
    "durationLabel": "5 Min.",
    "audio": "https://salon5.correctiv.net/audio/@salon5_erklart/kurz-erklaert-das-wahlprogramm-der-spd-9tscj.mp3"
   },
   {
    "id": "5d13f097-1c2e-11ec-9be9-a85e453daa56",
    "title": "Kurz Erklärt: Das Wahlprogramm der AfD",
    "date": "2025-03-03T13:44:03.000Z",
    "durationLabel": "6 Min.",
    "audio": "https://salon5.correctiv.net/audio/@salon5_erklart/kurz-erklaert-das-wahlprogramm-der-afd-mw8sf.mp3"
   },
   {
    "id": "912a62b6-1d0d-11ec-9be9-a85e453daa56",
    "title": "Kurz Erklärt: Das Wahlprogramm der Linken",
    "date": "2025-03-03T13:43:53.000Z",
    "durationLabel": "7 Min.",
    "audio": "https://salon5.correctiv.net/audio/@salon5_erklart/kurz-erklaert-das-wahlprogramm-der-linken-fwzwy.mp3"
   },
   {
    "id": "e6239973-1d1a-11ec-9be9-a85e453daa56",
    "title": "Kurz Erklärt: Das Wahlprogramm der FDP",
    "date": "2025-03-03T13:43:44.000Z",
    "durationLabel": "8 Min.",
    "audio": "https://salon5.correctiv.net/audio/@salon5_erklart/kurz-erklaert-das-wahlprogramm-der-fdp-vseca.mp3"
   },
   {
    "id": "b176171f-f326-11ed-84ae-a85e453daa56",
    "title": "Kurz Erklärt: Der Wald",
    "date": "2025-03-03T13:43:33.000Z",
    "durationLabel": "4 Min.",
    "audio": "https://salon5.correctiv.net/audio/@salon5_erklart/kurz-erklaert-der-wald-vqbzt.mp3"
   },
   {
    "id": "548f1657-09d5-11ee-84ae-a85e453daa56",
    "title": "KurzErklärt: Bürgerentscheid",
    "date": "2025-03-03T13:43:22.000Z",
    "durationLabel": "2 Min.",
    "audio": "https://salon5.correctiv.net/audio/@salon5_erklart/kurzerklaert-buergerentscheid-okmkt.mp3"
   },
   {
    "id": "d175e8eb-1437-11ee-84ae-a85e453daa56",
    "title": "Kurz Erklärt: Die Geschichte von Queer-Pride und dem CSD",
    "date": "2025-03-03T13:43:07.000Z",
    "durationLabel": "3 Min.",
    "audio": "https://salon5.correctiv.net/audio/@salon5_erklart/kurz-erklaert-die-geschichte-von-queer-pride-und-dem-csd-hemij.mp3"
   },
   {
    "id": "adef5832-402f-11ee-84ae-a85e453daa56",
    "title": "Kurz erklärt: Taschengeld",
    "date": "2025-03-03T13:42:48.000Z",
    "durationLabel": "5 Min.",
    "audio": "https://salon5.correctiv.net/audio/@salon5_erklart/kurz-erklaert-taschengeld-4kb83.mp3"
   }
  ]
 },
 "politik": {
  "id": "politik",
  "title": "Geld, Macht und Leben",
  "publisher": "Salon5",
  "description": "Du hörst nur das Wort “Politik” und schaltest direkt ab? So geht es vielen von uns! In dieser Podcast-Serie dreht sich alles um Politik, Wirtschaft und unsere Gesellschaft. Wir zeigen: Das muss gar nicht so langweilig sein! Wir sprechen üb…",
  "imageUrl": "https://salon5.correctiv.net/media/podcasts/politik/cover_feed.png",
  "episodes": [
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/welche-vorurteile-begegnen-uns-bei-unseren-hobbies",
    "title": "Welche Vorurteile begegnen uns bei unseren Hobbies?",
    "date": "2026-07-24T08:31:08.000Z",
    "durationLabel": "19 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/welche-vorurteile-begegnen-uns-bei-unseren-hobbies.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/jva-goes-schule-interview-mit-werner-herkert",
    "title": "JVA goes Schule - Interview mit Werner Herkert",
    "date": "2026-07-22T23:00:00.000Z",
    "durationLabel": "47 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/jva-goes-schule-interview-mit-werner-herkert.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/ki-und-freizeit-passt-das",
    "title": "KI und Freizeit, passt das?",
    "date": "2026-07-14T09:16:36.000Z",
    "durationLabel": "28 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/ki-und-freizeit-passt-das.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/wie-interessant-ist-das-global-media-forum-der-deutschen-welle-fur-jugendliche",
    "title": "Wie interessant ist das Global Media Forum der Deutschen Welle für Jugendliche?",
    "date": "2026-07-01T11:18:05.000Z",
    "durationLabel": "40 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/wie-interessant-ist-das-global-media-forum-der-deutschen-welle-fur-jugendliche.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/was-zahlen-wir-fur-social-media",
    "title": "Was zahlen wir für Social Media?",
    "date": "2026-06-29T22:01:00.000Z",
    "durationLabel": "25 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/was-zahlen-wir-fur-social-media.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/kein-social-media-mehr-fur-jugendliche-das-sagt-eine-expertin",
    "title": "Kein Social Media mehr für Jugendliche? Das sagt eine Expertin!",
    "date": "2026-06-25T22:00:00.000Z",
    "durationLabel": "16 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/kein-social-media-mehr-fur-jugendliche-das-sagt-eine-expertin.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/rennt-nicht-geht-konsumieren-wir-zu-viel",
    "title": "Rennt nicht, geht! Konsumieren wir zu viel?",
    "date": "2026-06-08T11:26:44.000Z",
    "durationLabel": "21 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/rennt-nicht-geht-konsumieren-wir-zu-viel.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/ordnung-im-kopf-aufraumexpertin-gibt-tipps",
    "title": "Ordnung im Kopf: Aufräumexpertin gibt Tipps",
    "date": "2026-06-01T22:01:00.000Z",
    "durationLabel": "24 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/ordnung-im-kopf-aufraumexpertin-gibt-tipps.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/schummeln-fur-den-fuhrerschein",
    "title": "Schummeln für den Führerschein?",
    "date": "2026-05-13T10:38:55.000Z",
    "durationLabel": "14 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/schummeln-fur-den-fuhrerschein.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/ein-jahr-bundesregierung-warum-wir-salty-sind",
    "title": "Ein Jahr Bundesregierung: Warum wir salty sind",
    "date": "2026-05-07T00:00:00.000Z",
    "durationLabel": "18 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/ein-jahr-bundesregierung-warum-wir-salty-sind.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/recap-ein-jahr-bundesregierung",
    "title": "Recap: Ein Jahr Bundesregierung",
    "date": "2026-05-04T23:00:00.000Z",
    "durationLabel": "5 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/recap-ein-jahr-bundesregierung.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/zu-besuch-beim-europaischen-jugendparlament",
    "title": "Zu Besuch beim Europäischen Jugendparlament",
    "date": "2026-04-09T09:24:15.000Z",
    "durationLabel": "19 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/zu-besuch-beim-europaischen-jugendparlament.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/klassismus-wie-unsere-soziale-herkunft-unser-leben-bestimmt",
    "title": "Klassismus: Wie unsere soziale Herkunft unser Leben bestimmt",
    "date": "2026-04-06T22:01:00.000Z",
    "durationLabel": "3 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/klassismus-wie-unsere-soziale-herkunft-unser-leben-bestimmt.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/schaufenstergesprach-warum-geht-jemand-freiwillig-zum-wehrdienst-nikos",
    "title": "Schaufenstergespräch: Warum geht jemand freiwillig zum Wehrdienst, Nikos?",
    "date": "2026-04-02T08:48:40.000Z",
    "durationLabel": "56 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/schaufenstergesprach-warum-geht-jemand-freiwillig-zum-wehrdienst-nikos.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/wie-viel-wusste-der-vatikan-uber-den-missbrauch-in-der-katholischen-kirche",
    "title": "Wie viel wusste der Vatikan über den Missbrauch in der katholischen Kirche?",
    "date": "2026-03-31T10:28:07.000Z",
    "durationLabel": "35 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/wie-viel-wusste-der-vatikan-uber-den-missbrauch-in-der-katholischen-kirche.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/interview-mit-philipp-dienstbier-was-ist-da-jetzt-eigentlich-im-iran-passiert",
    "title": "Interview mit Philipp Dienstbier: Was ist da jetzt eigentlich im Iran passiert?",
    "date": "2026-03-06T08:44:58.000Z",
    "durationLabel": "24 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/interview-mit-philipp-dienstbier-was-ist-da-jetzt-eigentlich-im-iran-passiert.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/was-bringt-ein-handy-und-social-media-verbot",
    "title": "Was bringt ein Handy- und Social-Media-Verbot?",
    "date": "2026-02-09T10:44:27.000Z",
    "durationLabel": "13 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/was-bringt-ein-handy-und-social-media-verbot.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/kurz-erklart-cybermobbing-und-seine-folgen",
    "title": "Kurz erklärt: Cybermobbing und seine Folgen",
    "date": "2026-02-09T10:39:06.000Z",
    "durationLabel": "5 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/kurz-erklart-cybermobbing-und-seine-folgen.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/kurz-erklart-darum-steht-gronland-so-im-fokus",
    "title": "Kurz Erklärt: Darum steht Grönland so im Fokus",
    "date": "2026-02-06T08:44:48.000Z",
    "durationLabel": "4 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/kurz-erklart-darum-steht-gronland-so-im-fokus.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@politik/episodes/warum-plotzlich-alle-uber-gronland-reden",
    "title": "Warum plötzlich alle über Grönland reden",
    "date": "2026-02-04T10:32:13.000Z",
    "durationLabel": "14 Min.",
    "audio": "https://salon5.correctiv.net/audio/@politik/warum-plotzlich-alle-uber-gronland-reden.mp3"
   }
  ]
 },
 "europa_was_geht": {
  "id": "europa_was_geht",
  "title": "Europa, was geht?",
  "publisher": "Salon5",
  "description": "🗳️ Europa wählt! Am 9. Juni ist bei uns in Deutschland Europawahl und Salon5 hat die wichtigsten Infos für euch. Wir sprechen mit Expertinnen und Experten über die wichtigsten Themen zur Europawahl, interviewen die Spitzenkandidatinnen un…",
  "imageUrl": "https://salon5.correctiv.net/media/podcasts/europa_was_geht/cover_feed.png",
  "episodes": [
   {
    "id": "85d4f8fd-45cd-11ef-ac9c-a85e453daa56",
    "title": "Klimaschnack in Greifswald: Wir besprechen die Ergebnisse der Europawahl",
    "date": "2024-07-19T12:50:37.000Z",
    "durationLabel": "20 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/klimaschnack-in-greifswald-wir-besprechen-die-ergebnisse-der-europawahl-ipdpy.mp3"
   },
   {
    "id": "8df62a75-299c-11ef-ac9c-a85e453daa56",
    "title": "Stimmen zur EU-Wahl: Wie gefährlich ist ein Rechtsruck?",
    "date": "2024-06-13T15:49:40.000Z",
    "durationLabel": "5 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/stimmen-zur-eu-wahl-wie-gefaehrlich-ist-ein-rechtsruck-swau8.wav"
   },
   {
    "id": "08be4447-2341-11ef-ac9c-a85e453daa56",
    "title": "Lobbyarbeit für ein Bundesland – das macht die NRW-Landesvertretung in Brüssel",
    "date": "2024-06-05T13:39:15.000Z",
    "durationLabel": "13 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/lobbyarbeit-fuer-ein-bundesland-das-macht-die-nrw-landesvertretung-in-bruessel-ylsst.mp3"
   },
   {
    "id": "b5addc27-2340-11ef-ac9c-a85e453daa56",
    "title": "Die EU - nichts für Jugendliche?",
    "date": "2024-06-05T13:37:05.000Z",
    "durationLabel": "19 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/die-eu-nichts-fuer-jugendliche-yylji.mp3"
   },
   {
    "id": "53ecbbf6-2340-11ef-ac9c-a85e453daa56",
    "title": "Die EU-Klimapolitik - in unmittelbarer Gefahr?",
    "date": "2024-06-05T13:34:21.000Z",
    "durationLabel": "38 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/die-eu-klimapolitik-in-unmittelbarer-gefahr-shvq9.mp3"
   },
   {
    "id": "bd92a9d9-233f-11ef-ac9c-a85e453daa56",
    "title": "Macht die EU genug fürs Klima?",
    "date": "2024-06-05T13:30:10.000Z",
    "durationLabel": "16 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/macht-die-eu-genug-fuers-klima-hnpjq.mp3"
   },
   {
    "id": "75b0b6de-219b-11ef-ac9c-a85e453daa56",
    "title": "Warum europäische Schulen einen Digitalisierungs-Plan brauchen",
    "date": "2024-06-03T11:21:40.000Z",
    "durationLabel": "26 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/warum-europaeische-schulen-einen-digitalisierungs-plan-brauchen-cdqfv.mp3"
   },
   {
    "id": "2fe1a39b-219b-11ef-ac9c-a85e453daa56",
    "title": "Deep Fakes im Europawahlkampf",
    "date": "2024-06-03T11:19:42.000Z",
    "durationLabel": "22 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/deep-fakes-im-europawahlkampf-lv6jd.mp3"
   },
   {
    "id": "9f51feb4-219a-11ef-ac9c-a85e453daa56",
    "title": "Kreislaufwirtschaft: Der Schlüssel für Nachhaltigkeit?",
    "date": "2024-06-03T11:15:39.000Z",
    "durationLabel": "17 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/kreislaufwirtschaft-der-schluessel-fuer-nachhaltigkeit-aaqvx.mp3"
   },
   {
    "id": "f3fe8bf7-2199-11ef-ac9c-a85e453daa56",
    "title": "Schaufenstergespräch mit Andreas Zick",
    "date": "2024-06-03T11:10:52.000Z",
    "durationLabel": "74 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/schaufenstergespraech-mit-andreas-zick-unqw0.mp3"
   },
   {
    "id": "23a09cf2-1f5a-11ef-ac9c-a85e453daa56",
    "title": "Auf TikTok über NS-Verbrechen aufklären",
    "date": "2024-05-31T14:29:03.000Z",
    "durationLabel": "33 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/auf-tiktok-ueber-ns-verbrechen-aufklaeren-d4i6o.mp3"
   },
   {
    "id": "ce7f3f5d-1f59-11ef-ac9c-a85e453daa56",
    "title": "EU-Jugendvertreter:innen: Wer die Jugend in Deutschland auf EU-Ebene vertritt",
    "date": "2024-05-31T14:26:40.000Z",
    "durationLabel": "40 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/eu-jugendvertreter-innen-wer-die-jugend-in-deutschland-auf-eu-ebene-vertritt-yoxlm.mp3"
   },
   {
    "id": "2a09af2b-1f59-11ef-ac9c-a85e453daa56",
    "title": "Europa und Demokratie - Ist Europapolitik wichtig für Jugendliche?",
    "date": "2024-05-31T14:22:01.000Z",
    "durationLabel": "33 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/europa-und-demokratie-ist-europapolitik-wichtig-fuer-jugendliche-14osx.mp3"
   },
   {
    "id": "9ad8be9c-1f58-11ef-ac9c-a85e453daa56",
    "title": "Mit 16 schon wählen können? - Jugendliche und die Europawahl",
    "date": "2024-05-31T14:18:01.000Z",
    "durationLabel": "27 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/mit-16-schon-waehlen-koennen-jugendliche-und-die-europawahl-l0ado.mp3"
   },
   {
    "id": "396d3fed-1d9e-11ef-ac9c-a85e453daa56",
    "title": "Darum ist der Schengen-Raum wichtig für unsere Reisefreiheit!",
    "date": "2024-05-29T09:31:22.000Z",
    "durationLabel": "22 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/darum-ist-der-schengen-raum-wichtig-fuer-unsere-reisefreiheit-kfymm.mp3"
   },
   {
    "id": "de0c4b3b-1d9d-11ef-ac9c-a85e453daa56",
    "title": "Ganz alleine im Ausland nach dem Abi?",
    "date": "2024-05-29T09:28:50.000Z",
    "durationLabel": "19 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/ganz-alleine-im-ausland-nach-dem-abi-jgefv.mp3"
   },
   {
    "id": "dc983b02-181f-11ef-ac9c-a85e453daa56",
    "title": "Warum ist Europa für Jugendliche so wichtig, Frau Rackete?",
    "date": "2024-05-28T09:44:15.000Z",
    "durationLabel": "20 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/warum-ist-europa-fuer-jugendliche-so-wichtig-frau-rackete-kmj8t.mp3"
   },
   {
    "id": "2ad76fb9-181f-11ef-ac9c-a85e453daa56",
    "title": "Warum ist Europa für Jugendliche so wichtig, Herr Boeselager?",
    "date": "2024-05-27T09:39:08.000Z",
    "durationLabel": "26 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/warum-ist-europa-fuer-jugendliche-so-wichtig-herr-boeselager-ckbkw.mp3"
   },
   {
    "id": "9a4afdc0-181e-11ef-ac9c-a85e453daa56",
    "title": "Warum ist Europa für Jugendliche so wichtig, Herr Schnarr?",
    "date": "2024-05-26T09:35:13.000Z",
    "durationLabel": "13 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/warum-ist-europa-fuer-jugendliche-so-wichtig-herr-schnarr-frzkk.mp3"
   },
   {
    "id": "d7f48aca-181d-11ef-ac9c-a85e453daa56",
    "title": "Warum ist Europa für Jugendliche so wichtig, Frau Strack-Zimmermann?",
    "date": "2024-05-25T09:29:41.000Z",
    "durationLabel": "19 Min.",
    "audio": "https://salon5.correctiv.net/audio/@europa_was_geht/warum-ist-europa-fuer-jugendliche-so-wichtig-frau-strack-zimmermann-a5yfe.mp3"
   }
  ]
 },
 "sport": {
  "id": "sport",
  "title": "Workout für die Ohren",
  "publisher": "Salon5",
  "description": "Couch-Potatoes und Sport- Junkies aufgepasst! Sport ist für alle da. In dieser Podcast-Reihe sprechen wir über alle wichtigen Themen rund um alle Sportarten: Probleme im Sportunterricht, mentaler Druck von Talenten und Profis oder Sexismus…",
  "imageUrl": "https://salon5.correctiv.net/media/podcasts/sport/cover_feed.png",
  "episodes": [
   {
    "id": "https://salon5.correctiv.net/@sport/episodes/wm-fieber-aber-zu-welchem-preis",
    "title": "WM-Fieber – aber zu welchem Preis?",
    "date": "2026-06-17T10:24:22.000Z",
    "durationLabel": "13 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/wm-fieber-aber-zu-welchem-preis.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@sport/episodes/wm-und-co-wie-beeinflussen-grose-sportereignisse-die-gesellschaft",
    "title": "WM und Co.: Wie beeinflussen große Sportereignisse die Gesellschaft?",
    "date": "2026-06-10T11:49:17.000Z",
    "durationLabel": "26 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/wm-und-co-wie-beeinflussen-grose-sportereignisse-die-gesellschaft.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@sport/episodes/neu-im-gym-uber-motivation-disziplin-und-hemmungen",
    "title": "Neu im Gym: Über Motivation, Disziplin und Hemmungen",
    "date": "2026-06-02T22:01:00.000Z",
    "durationLabel": "21 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/neu-im-gym-uber-motivation-disziplin-und-hemmungen.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@sport/episodes/sport-pendeln-doomscrolling-das-machen-wir-in-unserer-freizeit",
    "title": "Sport, Pendeln, Doomscrolling: Das machen wir in unserer Freizeit",
    "date": "2025-08-22T22:01:00.000Z",
    "durationLabel": "21 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/sport-pendeln-doomscrolling-das-machen-wir-in-unserer-freizeit.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@sport/episodes/olympia-fur-studis-live-bei-den-fisu-world-university-games",
    "title": "Olympia für Studis – live bei den FISU World University Games",
    "date": "2025-07-29T11:51:04.000Z",
    "durationLabel": "43 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/olympia-fur-studis-live-bei-den-fisu-world-university-games.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@sport/episodes/sexuelle-gewalt-im-jugendfusball",
    "title": "Sexuelle Gewalt im Jugendfußball",
    "date": "2025-04-03T15:52:49.000Z",
    "durationLabel": "24 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/sexuelle-gewalt-im-jugendfusball.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@sport/episodes/was-ist-die-formel-1",
    "title": "Was ist die Formel 1?",
    "date": "2025-03-14T09:22:36.000Z",
    "durationLabel": "3 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/was-ist-die-formel-1.mp3"
   },
   {
    "id": "d267ee75-e563-11ef-97fe-a85e453daa56",
    "title": "Gehören Fußball und Politik zusammen?",
    "date": "2025-02-07T14:57:10.000Z",
    "durationLabel": "4 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/gehoeren-fussball-und-politik-zusammen-jy9ng.mp3"
   },
   {
    "id": "51428f84-3e0b-11ef-ac9c-a85e453daa56",
    "title": "Kurz erklärt: Welche Mythen übers Gym stimmen wirklich?",
    "date": "2024-07-09T15:52:56.000Z",
    "durationLabel": "4 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/kurz-erklaert-welche-mythen-uebers-gym-stimmen-wirklich-xktpf.mp3"
   },
   {
    "id": "738a17fc-3e0a-11ef-ac9c-a85e453daa56",
    "title": "Jürgen Martschukat über das Zeitalter der Fitness",
    "date": "2024-07-09T15:46:42.000Z",
    "durationLabel": "26 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/juergen-martschukat-ueber-das-zeitalter-der-fitness-yykhw.mp3"
   },
   {
    "id": "bd8085d5-3d42-11ef-ac9c-a85e453daa56",
    "title": "So geht es uns im Gym",
    "date": "2024-07-08T15:57:07.000Z",
    "durationLabel": "11 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/so-geht-es-uns-im-gym-6pt4m.mp3"
   },
   {
    "id": "eb2feef0-3ad7-11ef-ac9c-a85e453daa56",
    "title": "Dicke Muskeln um jeden Preis – was ihr über Anabolika wissen müsst!",
    "date": "2024-07-05T14:07:27.000Z",
    "durationLabel": "3 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/dicke-muskeln-um-jeden-preis-was-ihr-ueber-anabolika-wissen-muesst-jf1sk.mp3"
   },
   {
    "id": "5e47cd4f-39fc-11ef-ac9c-a85e453daa56",
    "title": "Euro 2024: Deutschland vor dem Viertelfinale gegen Spanien",
    "date": "2024-07-04T11:55:49.000Z",
    "durationLabel": "6 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/euro-2024-deutschland-vor-dem-viertelfinale-gegen-spanien-nvn1a.wav"
   },
   {
    "id": "5450f3b3-2e40-11ef-ac9c-a85e453daa56",
    "title": "Nachhaltigste EM ever? – Das sind die Ergebnisse unsere Recherche",
    "date": "2024-06-19T13:32:05.000Z",
    "durationLabel": "15 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/nachhaltigste-em-ever-das-sind-die-ergebnisse-unsere-recherche-utdsy.mp3"
   },
   {
    "id": "d896a30d-2e18-11ef-ac9c-a85e453daa56",
    "title": "Wie nachhaltig ist die Euro 2024?",
    "date": "2024-06-19T08:49:25.000Z",
    "durationLabel": "21 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/wie-nachhaltig-ist-die-euro-2024-qz6as.mp3"
   },
   {
    "id": "a579e692-2e18-11ef-ac9c-a85e453daa56",
    "title": "Interview mit der Deutschen Umwelthilfe: Ist die Euro 2024 die nachhaltigste EM ever?",
    "date": "2024-06-19T08:48:02.000Z",
    "durationLabel": "16 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/interview-mit-der-deutschen-umwelthilfe-ist-die-euro-2024-die-nachhaltigste-em-ever-k6plo.mp3"
   },
   {
    "id": "c741edbc-2e17-11ef-ac9c-a85e453daa56",
    "title": "EM in Deutschland:Public Viewing, Deutschlandfahnen und die Nationalhymne",
    "date": "2024-06-19T08:41:49.000Z",
    "durationLabel": "8 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/em-in-deutschland-public-viewing-deutschlandfahnen-und-die-nationalhymne-mqbzm.mp3"
   },
   {
    "id": "8ef19912-2e17-11ef-ac9c-a85e453daa56",
    "title": "UEFA vs. Städte - Wer sind die wahren Gewinner der Fußball-EM?",
    "date": "2024-06-19T08:40:15.000Z",
    "durationLabel": "20 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/uefa-vs-staedte-wer-sind-die-wahren-gewinner-der-fussball-em-wdsi9.mp3"
   },
   {
    "id": "a3f16c96-2ca9-11ef-ac9c-a85e453daa56",
    "title": "Wer gewinnt die EM 2024?",
    "date": "2024-06-17T13:00:53.000Z",
    "durationLabel": "8 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/wer-gewinnt-die-em-2024-pufvw.mp3"
   },
   {
    "id": "19403b86-299e-11ef-ac9c-a85e453daa56",
    "title": "Die wichtigsten Zahlen zur Euro 2024",
    "date": "2024-06-13T16:00:43.000Z",
    "durationLabel": "2 Min.",
    "audio": "https://salon5.correctiv.net/audio/@sport/die-wichtigsten-zahlen-zur-euro-2024-vsade.mp3"
   }
  ]
 },
 "pyjama_party": {
  "id": "pyjama_party",
  "title": "Pyjama Party",
  "publisher": "Salon5",
  "description": "Der erste Kuss, der erste Sex, die erste Beziehung – viele Jugendliche machen jetzt gerade genau diese Erfahrungen. In unserer Podcast-Reihe Pyjama Party geht´s um eure Themen rund um Liebe, Sex und Freundschaft. Wir sprechen über soziale…",
  "imageUrl": "https://salon5.correctiv.net/media/podcasts/pyjama_party/cover_feed.png",
  "episodes": [
   {
    "id": "https://salon5.correctiv.net/@pyjama_party/episodes/sind-wir-unsere-hobbys",
    "title": "Sind wir unsere Hobbys?",
    "date": "2026-07-06T22:00:00.000Z",
    "durationLabel": "20 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/sind-wir-unsere-hobbys.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pyjama_party/episodes/wg-horrorstorys-zum-kotzen-wortwortlich",
    "title": "WG-Horrorstorys zum Kotzen (wortwörtlich)",
    "date": "2026-03-20T09:00:00.000Z",
    "durationLabel": "26 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/wg-horrorstorys-zum-kotzen-wortwortlich.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pyjama_party/episodes/was-sagen-unsere-jugendreporter-zum-jugendwort-2025",
    "title": "Was sagen unsere Jugendreporter zum Jugendwort 2025?",
    "date": "2025-10-24T23:00:00.000Z",
    "durationLabel": "12 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/was-sagen-unsere-jugendreporter-zum-jugendwort-2025.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pyjama_party/episodes/fomo-im-sommer",
    "title": "FOMO im Sommer",
    "date": "2025-07-16T07:17:33.000Z",
    "durationLabel": "18 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/fomo-im-sommer.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pyjama_party/episodes/so-sollte-sexualkunde-an-schulen-sein",
    "title": "So sollte Sexualkunde an Schulen sein!",
    "date": "2025-03-07T11:38:07.000Z",
    "durationLabel": "30 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/so-sollte-sexualkunde-an-schulen-sein.mp3"
   },
   {
    "id": "https://salon5.correctiv.net/@pyjama_party/episodes/verhutungsmittel-geht-das-nicht-gunstiger",
    "title": "Verhütungsmittel: Geht das nicht günstiger?",
    "date": "2025-03-05T15:22:52.000Z",
    "durationLabel": "3 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/verhutungsmittel-geht-das-nicht-gunstiger.mp3"
   },
   {
    "id": "f3aea5ac-f819-11ef-97fe-a85e453daa56",
    "title": "Kurz erklärt: Was ist der Pearlindex",
    "date": "2025-03-03T10:26:14.000Z",
    "durationLabel": "3 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/kurz-erklaert-was-ist-der-pearlindex-6rgor.mp3"
   },
   {
    "id": "c78d416c-f818-11ef-97fe-a85e453daa56",
    "title": "Verhütung: Wie aufgeklärt sind Jugendliche?",
    "date": "2025-03-03T10:17:50.000Z",
    "durationLabel": "10 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/verhuetung-wie-aufgeklaert-sind-jugendliche-wjweh.mp3"
   },
   {
    "id": "307c9e17-f818-11ef-97fe-a85e453daa56",
    "title": "So verhüten Jugendliche!",
    "date": "2025-03-03T10:12:48.000Z",
    "durationLabel": "22 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/so-verhueten-jugendliche-tbjvp.mp3"
   },
   {
    "id": "2b930083-e54c-11ef-97fe-a85e453daa56",
    "title": "Unsere Red und Green Flags",
    "date": "2025-02-07T12:07:42.000Z",
    "durationLabel": "17 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/unsere-red-und-green-flags-iv3g9.mp3"
   },
   {
    "id": "ba131f2a-dff4-11ef-97fe-a85e453daa56",
    "title": "Friendship Break up - Wie geht das?",
    "date": "2025-01-31T16:59:21.000Z",
    "durationLabel": "12 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/friendship-break-up-wie-geht-das-is7n8.mp3"
   },
   {
    "id": "ddf54b06-c1eb-11ef-88b8-a85e453daa56",
    "title": "Unsere Highlights 2024",
    "date": "2024-12-24T11:40:20.000Z",
    "durationLabel": "28 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/unsere-highlights-2024-jzw1q.mp3"
   },
   {
    "id": "481af62e-beef-11ef-88b8-a85e453daa56",
    "title": "Was macht ihr an Weihnachten?",
    "date": "2024-12-20T16:27:12.000Z",
    "durationLabel": "26 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/was-macht-ihr-an-weihnachten-h6zqq.mp3"
   },
   {
    "id": "1c51ecec-a7df-11ef-88b8-a85e453daa56",
    "title": "Catcalling sichtbar machen: Pia Brauneis über ihre Mission mit “Catcalls of Bielefeld”",
    "date": "2024-11-21T08:03:28.000Z",
    "durationLabel": "24 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/catcalling-sichtbar-machen-pia-brauneis-ueber-ihre-mission-mit-catcalls-of-bielefeld-xbt9b.mp3"
   },
   {
    "id": "8be3a5b1-798f-11ef-88b8-a85e453daa56",
    "title": "Was machen die “couple goals” auf Social Media mit uns?",
    "date": "2024-09-23T09:38:05.000Z",
    "durationLabel": "24 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/was-machen-die-couple-goals-auf-social-media-mit-uns-9afnx.mp3"
   },
   {
    "id": "8dbb2293-798e-11ef-88b8-a85e453daa56",
    "title": "Love Scamming und Love Gurus. Warum sind wir eigentlich so anfällig dafür?",
    "date": "2024-09-23T09:30:59.000Z",
    "durationLabel": "13 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/love-scamming-und-love-gurus-warum-sind-wir-eigentlich-so-anfaellig-dafuer-8ck5l.mp3"
   },
   {
    "id": "378829af-798d-11ef-88b8-a85e453daa56",
    "title": "Was sind die fünf Love Languages?",
    "date": "2024-09-23T09:21:23.000Z",
    "durationLabel": "30 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/was-sind-die-fuenf-love-languages-rzbvv.mp3"
   },
   {
    "id": "78596ff7-7430-11ef-88b8-a85e453daa56",
    "title": "Der erste große Crush: So war es bei uns",
    "date": "2024-09-16T13:34:55.000Z",
    "durationLabel": "31 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/der-erste-grosse-crush-so-war-es-bei-uns-pejbg.mp3"
   },
   {
    "id": "7c469358-6b77-11ef-88b8-a85e453daa56",
    "title": "Kurz erklärt: Was passiert in unserem Gehirn, wenn wir schlafen?",
    "date": "2024-09-05T11:10:31.000Z",
    "durationLabel": "2 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/kurz-erklaert-was-passiert-in-unserem-gehirn-wenn-wir-schlafen-66rah.mp3"
   },
   {
    "id": "a9bd23ab-4a9a-11ef-ac9c-a85e453daa56",
    "title": "Wie prägen rechte Ideologien das Männerbild?",
    "date": "2024-07-25T15:29:13.000Z",
    "durationLabel": "45 Min.",
    "audio": "https://salon5.correctiv.net/audio/@pyjama_party/wie-praegen-rechte-ideologien-das-maennerbild-lwiy3.mp3"
   }
  ]
 }
};
