/**
 * Converts ../wp-design-tokens/css/theme.css into NativeScript-compatible SCSS.
 *
 * NativeScript CSS knows no rem, no :root and no unitless line-height —
 * that is why this script is the only permitted way to bring tokens into
 * the app. Never import theme.css directly.
 *
 * Rules:
 *   rem            → dip (×16, unitless)
 *   px             → unitless dip
 *   s (duration)   → ms (number, for animation APIs)
 *   :root          → .ns-root (class on the root view)
 *   @media blocks  → ignored (app is phone-only, no dark mode in the prototype)
 *
 * Usage: npm run tokens
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(__dirname, '../../wp-design-tokens/css/theme.css');
const OUT = resolve(__dirname, '../src/styles/tokens.generated.scss');

const css = readFileSync(SRC, 'utf8');

// Extract the first :root block (mobile values; ignore @media overrides).
const rootMatch = css.match(/:root\s*\{([\s\S]*?)\}/);
if (!rootMatch) throw new Error('No :root block found in theme.css');

const declarations = [];
for (const line of rootMatch[1].split('\n')) {
  const m = line.match(/^\s*(--var-[\w-]+)\s*:\s*([^;]+);/);
  if (m) declarations.push({ name: m[1], value: m[2].trim() });
}

const remToDip = (v) => Math.round(parseFloat(v) * 16 * 100) / 100;

function convert(name, value) {
  // Keep font stacks and references to other variables unchanged.
  if (value.startsWith('var(')) return null; // aliases (font-serif/font-sans) handled separately
  if (value.includes('"')) return { value, kind: 'string' };
  const rem = value.match(/^(-?[\d.]+)rem$/);
  if (rem) return { value: remToDip(rem[1]), kind: 'number' };
  const px = value.match(/^(-?[\d.]+)px$/);
  if (px) return { value: parseFloat(px[1]), kind: 'number' };
  const sec = value.match(/^(-?[\d.]+)s$/);
  if (sec) return { value: parseFloat(sec[1]) * 1000, kind: 'number' };
  return { value, kind: 'raw' }; // colors, unitless numbers (leading, font weights)
}

const scssVars = [];
const cssVars = [];
for (const { name, value } of declarations) {
  const conv = convert(name, value);
  if (!conv) continue;
  const scssName = name.replace(/^--var-/, '$');
  scssVars.push(`${scssName}: ${conv.value};`);
  if (conv.kind !== 'string') {
    cssVars.push(`  ${name.replace(/^--var-/, '--')}: ${conv.value};`);
  }
}

// Utility classes — deliberately only the small subset that NS CSS supports.
const colors = declarations.filter((d) => d.name.startsWith('--var-color-'));
const spacings = declarations.filter(
  (d) => d.name.startsWith('--var-spacing-') && d.name !== '--var-spacing',
);
const radii = declarations.filter((d) => d.name.startsWith('--var-radius-'));

const util = [];
for (const c of colors) {
  const key = c.name.replace('--var-color-', '');
  util.push(`.bg-${key} { background-color: ${c.value}; }`);
  util.push(`.text-${key} { color: ${c.value}; }`);
}
for (const s of spacings) {
  const key = s.name.replace('--var-spacing-', '');
  const dip = remToDip(s.value);
  util.push(`.p-${key} { padding: ${dip}; }`);
  util.push(`.px-${key} { padding-left: ${dip}; padding-right: ${dip}; }`);
  util.push(`.py-${key} { padding-top: ${dip}; padding-bottom: ${dip}; }`);
  util.push(`.m-${key} { margin: ${dip}; }`);
  util.push(`.mx-${key} { margin-left: ${dip}; margin-right: ${dip}; }`);
  util.push(`.my-${key} { margin-top: ${dip}; margin-bottom: ${dip}; }`);
  util.push(`.mt-${key} { margin-top: ${dip}; }`);
  util.push(`.mb-${key} { margin-bottom: ${dip}; }`);
}
for (const r of radii) {
  const key = r.name.replace('--var-radius-', '');
  util.push(`.rounded-${key} { border-radius: ${remToDip(r.value)}; }`);
}

const banner = `// GENERATED by scripts/sync-tokens.mjs from wp-design-tokens/css/theme.css
// DO NOT edit by hand — regenerate changes with \`npm run tokens\`.
`;

const out = `${banner}
// ── SCSS variables (build time) ─────────────────────────────────
${scssVars.join('\n')}

// ── CSS variables (runtime, var() in component styles) ─────────
.ns-root {
${cssVars.join('\n')}
}

// ── Utilities ───────────────────────────────────────────────────
${util.join('\n')}
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, out);
console.log(`tokens.generated.scss written (${scssVars.length} variables, ${util.length} utilities)`);
